# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.6.5


## Pandas

Para poder trabalhar com Pandas, você deve conhecer bem estas duas estruturas: Series e DataFrame.

Para importar o pandas, utilize: 
import pandas as pd

Você também pode utilizar: 
from pandas import Series, DataFrame  

Para atualizar o Pandas, abra o prompt de comando ou terminal e digite: pip install pandas -U

## Series

Series é um array unidimensional que contém um array de dados e um array de labels, chamado índice.


In [2]:
from pandas import Series

In [3]:
#!pip install pandas -U

In [4]:
import pandas as pd
pd.__version__

'1.0.3'

In [5]:
# Criando uma série sem especificar os índices
Obj = Series([67, 78, -56, 13])

In [6]:
Obj

0    67
1    78
2   -56
3    13
dtype: int64

In [7]:
type(Obj)

pandas.core.series.Series

In [8]:
Obj.values

array([ 67,  78, -56,  13], dtype=int64)

In [9]:
Obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
# Criando uma série e especificando os índices
Obj2 = Series([67, 78, -56, 13], index = ['a', 'b', 'c', 'd'])

In [11]:
Obj2

a    67
b    78
c   -56
d    13
dtype: int64

In [12]:
Obj2.values

array([ 67,  78, -56,  13], dtype=int64)

In [13]:
Obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
Obj2[Obj2 > 3]

a    67
b    78
d    13
dtype: int64

In [15]:
print(Obj2['b'])
Obj2[Obj2 == -56]

78


c   -56
dtype: int64

In [16]:
'c' in Obj2

True

In [17]:
# Criando uma série de dados passando um dicionário como parâmetro
dict = {'Futebol':5200, 'Tenis': 120, 'Natação':698, 'Volleyball':1550}

In [18]:
# Criando uma série a partir de um dicionário
Obj3 = Series(dict)

In [19]:
Obj3

Futebol       5200
Tenis          120
Natação        698
Volleyball    1550
dtype: int64

In [20]:
type(Obj3)

pandas.core.series.Series

In [21]:
# Criando uma lista
esportes = ['Futebol', 'Tenis', 'Natação', 'Basktetball']

In [22]:
# Criando uma serie e usando uma lista como índice
Obj4 = Series(dict, index=esportes)

In [23]:
Obj4

Futebol        5200.0
Tenis           120.0
Natação         698.0
Basktetball       NaN
dtype: float64

In [24]:
pd.isnull(Obj4)

Futebol        False
Tenis          False
Natação        False
Basktetball     True
dtype: bool

In [25]:
pd.notnull(Obj4)

Futebol         True
Tenis           True
Natação         True
Basktetball    False
dtype: bool

In [26]:
Obj4.isnull()

Futebol        False
Tenis          False
Natação        False
Basktetball     True
dtype: bool

In [27]:
# Concatenando Series. Se há coincidência de índices em ambos, soma os valores.
Obj3 + Obj4

Basktetball        NaN
Futebol        10400.0
Natação         1396.0
Tenis            240.0
Volleyball         NaN
dtype: float64

In [28]:
Obj4.name = 'população'

In [29]:
Obj4.index.name = 'esporte'

In [30]:
Obj4

esporte
Futebol        5200.0
Tenis           120.0
Natação         698.0
Basktetball       NaN
Name: população, dtype: float64

## Dataframes

Dataframes representam uma estrutura tabular semelhante a estrutura de uma planilha do Excel, contendo uma coleção de colunas em que cada uma pode ser um diferente tipo de valor (número, string, etc...). Os Dataframes possuem index e linhas e esta estrutura é muito semelhante a um dataframe em R. Os dados de um dataframe são armazenados e um ou mais blocos bidimensionais, ao invés de listas, dicionários ou alguma outra estrutura de array.

In [31]:
from pandas import DataFrame
#import pandas as pd

In [32]:
data = {'Estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'], 
        'Ano': [2002, 2003, 2004, 2005, 2006], 
        'População': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [33]:
frame = DataFrame(data)

In [34]:
frame

Estado   Ano  População
0  Santa Catarina  2002        1.5
1          Paraná  2003        1.7
2           Goiás  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [35]:
type(frame)

pandas.core.frame.DataFrame

In [36]:
DataFrame(data, columns = ['Ano', 'Estado', 'População'])

Ano          Estado  População
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [37]:
# Criando outro dataframe com os mesmo dados anteriores mas adicionando uma coluna
frame2 = DataFrame(data, columns = ['Ano', 'Estado', 'População', 'Débito'], 
                   index = ['um', 'dois', 'três', 'quatro', 'cinco'])

In [38]:
# Imprimindo o Dataframe
frame2

Ano          Estado  População Débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Paraná        1.7    NaN
três    2004           Goiás        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

In [39]:
# Imprimindo apenas uma coluna do Dataframe
frame2['Estado']

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: Estado, dtype: object

In [40]:
type(frame2)

pandas.core.frame.DataFrame

In [41]:
frame2.index

Index(['um', 'dois', 'três', 'quatro', 'cinco'], dtype='object')

In [42]:
frame2.columns

Index(['Ano', 'Estado', 'População', 'Débito'], dtype='object')

In [43]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, nan],
       [2003, 'Paraná', 1.7, nan],
       [2004, 'Goiás', 3.6, nan],
       [2005, 'Bahia', 2.4, nan],
       [2006, 'Minas Gerais', 2.9, nan]], dtype=object)

In [44]:
frame2.dtypes

Ano            int64
Estado        object
População    float64
Débito        object
dtype: object

In [45]:
frame2['Ano']

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [46]:
frame2.Ano

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [47]:
frame2[:2]

Ano          Estado  População Débito
um    2002  Santa Catarina        1.5    NaN
dois  2003          Paraná        1.7    NaN

## Usando NumPy e Pandas

In [48]:
# Importando o NumPy
import numpy as np

In [61]:
# Usando o NumPy para alimentar uma das colunas do dataframe
frame2['Débito'] = np.arange(5.)

In [60]:
frame2

Ano          Estado  População  Débito
um      2002  Santa Catarina        1.5       0
dois    2003          Paraná        1.7       1
três    2004           Goiás        3.6       2
quatro  2005           Bahia        2.4       3
cinco   2006    Minas Gerais        2.9       4

In [58]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Paraná', 1.7, 1.0],
       [2004, 'Goiás', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

In [62]:
# Resumo do Dataframe
frame2.describe()

Ano  População    Débito
count     5.000000   5.000000  5.000000
mean   2004.000000   2.420000  2.000000
std       1.581139   0.864292  1.581139
min    2002.000000   1.500000  0.000000
25%    2003.000000   1.700000  1.000000
50%    2004.000000   2.400000  2.000000
75%    2005.000000   2.900000  3.000000
max    2006.000000   3.600000  4.000000

In [63]:
frame2['dois':'quatro']

Ano  Estado  População  Débito
dois    2003  Paraná        1.7     1.0
três    2004   Goiás        3.6     2.0
quatro  2005   Bahia        2.4     3.0

In [72]:
# frame2 < 5
frame2[frame2['População'] < 5]

Ano          Estado  População  Débito
um      2002  Santa Catarina        1.5     0.0
dois    2003          Paraná        1.7     1.0
três    2004           Goiás        3.6     2.0
quatro  2005           Bahia        2.4     3.0
cinco   2006    Minas Gerais        2.9     4.0

## Localizando Registros Dentro do Dataframe

In [71]:
frame2.loc['quatro']

Ano           2005
Estado       Bahia
População      2.4
Débito           3
Name: quatro, dtype: object

In [73]:
frame2.iloc[2]

Ano           2004
Estado       Goiás
População      3.6
Débito           2
Name: três, dtype: object

## Invertendo as Colunas e Índices

In [74]:
# Criando um dicionário
web_stats = {'Dias':[1, 2, 3, 4, 5, 6, 7], 
             'Visitantes':[45, 23, 67, 78, 23, 12, 14], 
             'Taxas':[11, 22, 33, 44, 55, 66, 77]}

In [75]:
df = pd.DataFrame(web_stats)

In [76]:
print(df)

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77


In [77]:
# Visualizando uma coluna  index
print(df.set_index('Dias'))

      Visitantes  Taxas
Dias                   
1             45     11
2             23     22
3             67     33
4             78     44
5             23     55
6             12     66
7             14     77


In [80]:
print(df.head())

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55


In [81]:
print(df['Visitantes'])

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64


In [82]:
print(df[['Visitantes', 'Taxas']])

   Visitantes  Taxas
0          45     11
1          23     22
2          67     33
3          78     44
4          23     55
5          12     66
6          14     77


## Dataframes e Arquivos csv

In [ ]:
# Usando o método read_csv
df = pd.read_csv('salarios.csv')

In [ ]:
df

In [ ]:
# Usando o método read_table
df = pd.read_table('salarios.csv', sep = ',')

In [ ]:
df

In [ ]:
# No Windows use !type. No Mac ou Linux use !head
!head salarios.csv
# !type salarios.csv

In [ ]:
# Alterando o título das colunas
df = pd.read_csv('salarios.csv', names = ['a', 'b', 'c', 'd'])

In [ ]:
df

In [ ]:
import sys

In [ ]:
data = pd.read_csv('salarios.csv')

In [ ]:
data.to_csv(sys.stdout, sep = '|')

In [ ]:
# Criando um Dataframe
dates = pd.date_range('20180101', periods = 10)
df = pd.DataFrame(np.random.randn(10,4), index = dates, columns = list('ABCD'))

In [ ]:
df

In [ ]:
df.head()

In [ ]:
# quick data summary
df.describe()

In [ ]:
# Calculando a média
df.mean()

In [ ]:
# Pivot e cálculo da média
df.mean(1)

In [ ]:
# Usando métodos
df.apply(np.cumsum)

In [ ]:
# Merge de Dataframes
left = pd.DataFrame({'chave': ['chave1', 'chave2'], 'coluna1': [1, 2]})
right = pd.DataFrame({'chave': ['chave1', 'chave2'], 'coluna2': [4, 5]})
pd.merge(left, right, on='chave')

In [ ]:
# Adicionando um elemento ao Dataframe
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])

In [ ]:
df

In [ ]:
s = df.iloc[3]

In [ ]:
# Adicionando um elemento ao Dataframe
df.append(s, ignore_index=True)

## Time Series

In [ ]:
# Criando um range de datas com frequência de segundos
rng = pd.date_range('1/1/2020', periods = 50, freq = 'S')

In [ ]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index = rng)

In [ ]:
ts

In [ ]:
# Criando um range de datas com frequência de meses
rng = pd.date_range('1/1/2020', periods = 5, freq = 'M')
ts = pd.Series(np.random.randn(len(rng)), index = rng)
ts

## Plotting

In [ ]:
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline

In [ ]:
import matplotlib as mat
mat.__version__

In [ ]:
# Time Series Plot
ts = pd.Series(np.random.randn(500), index=pd.date_range('1/1/2020', periods = 500))
ts = ts.cumsum()
ts.plot()

In [ ]:
# DataFrame Plot
df = pd.DataFrame(np.random.randn(500, 4), index = ts.index, columns = ['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure(); df.plot(); plt.legend(loc = 'best')

## Outuput

In [ ]:
# Import
import os

In [ ]:
# Verificando se o arquivo existe. No Windows use !type teste-df-output.xlsx
!head teste-df-output.xlsx

In [ ]:
# Gerando um arquivo excel a partir de um Dataframe
df.to_excel('teste-df-output.xlsx', sheet_name='Sheet1')

In [ ]:
# Verificando se o arquivo existe. No Windows use !type teste-df-output.xlsx
!head teste-df-output.xlsx

In [ ]:
# Lendo o arquivo excel para um Dataframe
newDf2 = pd.read_excel('teste-df-output.xlsx', 'Sheet1', index_col = None, na_values = ['NA'])

In [ ]:
newDf2.head()

In [ ]:
os.remove('teste-df-output.xlsx')

In [ ]:
# Verificando se o arquivo existe. No Windows use !type teste-df-output.xlsx
!head teste-df-output.xlsx

Conheça a Formação Cientista de Dados, um programa completo, 100% online e 100% em português, com mais de 400 horas de carga horária, mais de 1.200 aulas em vídeos e 26 projetos, que vão ajudá-lo a se tornar um dos profissionais mais cobiçados do mercado de análise de dados. Clique no link abaixo, faça sua inscrição, comece hoje mesmo e aumente sua empregabilidade:

https://www.datascienceacademy.com.br/pages/formacao-cientista-de-dados

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>